# general settings
name: train_supernet_cityscape_8gpu_b3_120k_syncbn
model_type: OneShotModel
num_gpu: 8  # set num_gpu: 0 for cpu mode
manual_seed: 0
find_unused_parameters: True

# dataset and data loader settings
datasets:
  train:
    name: cityscapes_train
    type: Cityscape_Dataset
    data_dir: datasets/cityscapes/
    data_list: datasets/cityscapes/train.txt
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    input_size: [512,1024]
    scales: [0.5,2]
    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 3
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: cityscapes_val
    type: Cityscape_Dataset
    data_dir: datasets/cityscapes/
    data_list: datasets/cityscapes/val.txt
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    input_size: [1024,2048]
    num_worker_per_gpu: 4
    batch_size_per_gpu: 3

# network structures
supernet:
  type: iNASSupernet
  cfg: ~
  num_classes: 19
  activation: none
  output_level_ids: (0,2)

# path
path:
  pretrain_network: experiments/pretrained_models/search_space/checkpoint-28b11d7f.pth
  strict_load: false
  resume_state: ~
  param_key: state_dict

# training settings
train:
  optim:
    type: Adam
    lr: !!float 2e-4
    head_lr_mul: 10
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: PolynomialLRDecay
    max_decay_steps: 120000
    end_learning_rate: !!float 0
    power: 0.9

  total_iter: 120000
  warmup_iter: 1000

  multi_scale_training: false
  sync_bn: true

  # losses
  main_opt:
    type: DSCrossEntropyLoss
    weight: 1.0
    aux_weight: 0.4
    reduction: mean

  distill_opt:
    type: DSPixelWiseKLLoss
    weight: 0.2
    aux_weight: 0.4
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  finetune_bn_iters: 100
  output_transform: semseg # choices ["semseg", "sod"]
  metrics:
    MIOU:
      ignore_label: 255
      num_classes: 19


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!int 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
